# prevent Netlify npm install

[build]
publish = "docs/.vuepress/dist"
command = "pnpm install && pnpm build:package && pnpm docs:build"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--version"
